In [1]:
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("Week 1 Temperatures:")
print(temperatures_w1)

Week 1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

In [8]:
print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)

Shape: (7,)
Data Type: float64
Number of Elements: 7

In [9]:
temperatures_f = (temperatures_w1 * 9/5) + 32

print("Temperatures in Fahrenheit:")
print(temperatures_f)

print("Maximum Temperature:", np.max(temperatures_w1))
print("Minimum Temperature:", np.min(temperatures_w1))
print("Mean Temperature:", np.mean(temperatures_w1))

Temperatures in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144

In [10]:
print("First Three Days:")
print(temperatures_w1[:3])

print("Weekend Temperatures:")
print(temperatures_w1[-2:])

print("Middle Three Days:")
print(temperatures_w1[2:5])

First Three Days:
[22.5 25.3 20.8]
Weekend Temperatures:
[24.8 21.9]
Middle Three Days:
[20.8 23.4 26.1]

In [20]:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])

print("Temperatures for Two Weeks:")
print(temperatures)

Temperatures for Two Weeks:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

In [28]:
print("Shape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Elements:", temperatures.size)
print("Week 1:")
print(temperatures[0])

print("Week 2:")
print(temperatures[1])
print("Weekend Temperatures:")
print(temperatures[:,-2:])

Shape: (2, 7)
Data Type: float64
Total Elements: 14
Week 1:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2:
[19.2 22.5 21.3 24.  23.5 22.8 20.1]
Weekend Temperatures:
[[24.8 21.9]
 [22.8 20.1]]

In [30]:
import pandas as pd
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=["Rank1", "Rank2", "Rank3", "Rank4", "Rank5"])
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [31]:
print("1st Rank Mark:")
print(marks.iloc[0])
print("Top 3 Ranks:")
print(marks.loc[["Rank1", "Rank2", "Rank3"]])
print("3rd Rank Mark:")
print(marks.iloc[2])
print("Marks Greater Than 90:")
print(marks[marks > 90])

1st Rank Mark:
95
Top 3 Ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64
3rd Rank Mark:
89
Marks Greater Than 90:
Rank1    95
Rank2    92
dtype: int64

In [32]:
marks.loc["Rank1"] = 100
print("Updated Marks:")
print(marks)
marks = marks.drop("Rank5")
print("After Removing Rank5:")
print(marks)
cgpa = marks / 10
print("CGPA:")
print(cgpa)

Updated Marks:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64
After Removing Rank5:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

In [37]:

import pandas as pd

transactions = pd.DataFrame({"TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],"ProductCategory": ["Electronics", "Clothing", "Electronics", "Furniture","Clothing", "Electronics", "Furniture", "Clothing","Furniture", "Electronics"],"Region": ["North", "South", "North", "East", "West","North", "East", "West", "South", "North"],"Amount": [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [38]:
print("Full DataFrame:")
display(transactions)
print("First Five Rows:")
display(transactions.head())
print("Last Five Rows:")
display(transactions.tail())
print("Shape:")
print(transactions.shape)
print("Column Names:")
print(transactions.columns)
print("DataFrame Information:")
transactions.info()

Full DataFrame:

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

First Five Rows:

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Last Five Rows:

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Shape:
(10, 4)
Column Names:
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')
DataFrame Information:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     str
 2   Region           10 non-null     str
 3   Amount           10 non-null     int64
dtypes: int64(2), str(2)
memory usage: 593.0 bytes

In [41]:
filtered_data = transactions[(transactions["Region"] == "North") &(transactions["Amount"] > 200)]
print("North Region Transactions with Amount Greater Than 200:")
display(filtered_data)

North Region Transactions with Amount Greater Than 200:

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [43]:
print("Product Category Counts:")
print(transactions["ProductCategory"].value_counts())
print("Unique Regions:")
print(transactions["Region"].unique())

Product Category Counts:
ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64
Unique Regions:
<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [44]:
region_mean = transactions.groupby("Region")["Amount"].mean()
print("Mean Amount by Region:")
print(region_mean)

Mean Amount by Region:
Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [50]:
transactions = transactions[transactions["TransactionID"] != 109]
print("After Removing Transaction 109:")
display(transactions)

After Removing Transaction 109:

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

In [51]:
transactions["Discount"] = transactions["Amount"] * 0.10

In [52]:

transactions.loc[transactions["TransactionID"] == 102, "Amount"] = 165
print("After Updating Transaction 102:")
display(transactions)

After Updating Transaction 102:

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [53]:
transactions = transactions.drop(columns=["Discount"])
print("Final DataFrame:")
display(transactions)

Final DataFrame:

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400